### ISSUE TITLE
Typo in test_car.py

### ISSUE THREAD

**Issue by YiruMu** [vagabond-systems/forage-lyft-starter-repo#5]
<img width="546" alt="Screen Shot 2022-07-08 at 8 29 12 PM" src="https://user-images.githubusercontent.com/76975418/178084664-f4052ca4-bca1-4e6d-b6a8-9f5377cf79b4.png">
The second unit test for Palindrome should not assert False, since Palindrome has Spindler Battery which should be serviced every 2 years. If the last service was 3 years ago, it should be serviced.

**Comment by YiruMu** [comment]
tho the test is correct after upgrade

**Comment by aries15** [comment]
True. The existing code uses *4* so that passed the test, while the chart told us it's using *Spindler Battery*.

https://github.com/vagabond-systems/forage-lyft-starter-repo/blob/1c26f9cbad7b9bf859b3de73c4c65fb58e028a5f/engine/model/palindrome.py#L8
